services:
  - type: web
    name: tu-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"  # Importante: Render usa Linux, necesita build.sh
    startCommand: "gunicorn Backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tu-db-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: FRONTEND_URL
        value: "https://tufrontend.onrender.com"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

databases:
  - name: tu-db-postgres
    databaseName: login_jwuj
    user: gustavo
    plan: free